# Generated by Django 4.2.1 on 2025-03-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='home',
        ),
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default='123 Kieu Son Den', max_length=120),
        ),
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HomePerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_persons', to='api.home')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_homes', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.device')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.home'),
        ),
    ]
