# Generated by Django 4.2.1 on 2025-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_remove_person_home_home_address_alter_home_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='humidity',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='home',
            name='temperature',
            field=models.FloatField(default=27),
        ),
    ]
