# Generated by Django 4.2.1 on 2025-04-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_home_humidity_home_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('door', 'Door'), ('fan', 'Fan'), ('light', 'Light'), ('curtain', 'Curtain')], default='door', max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='home',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='api.home'),
        ),
        migrations.AlterField(
            model_name='device',
            name='home',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.home'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='off', max_length=10),
        ),
        migrations.DeleteModel(
            name='HomePerson',
        ),
    ]
