# Generated by Django 4.2.1 on 2025-04-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_type_person_home_alter_device_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.home'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='api.home'),
        ),
    ]
