# Generated by Django 4.2.1 on 2025-04-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_home_options_alter_home_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='password',
            field=models.CharField(default='666666', max_length=120),
        ),
    ]
