# Generated by Django 4.2.1 on 2025-04-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_home_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='home',
            managers=[
            ],
        ),
    ]
