# Generated by Django 4.2.1 on 2025-04-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom')], default='living_room', max_length=120),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='off', max_length=10),
        ),
    ]
