# Generated by Django 4.2.1 on 2025-04-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_home_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
