# Generated by Django 4.2.1 on 2025-04-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_home_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('open', 'Open'), ('close', 'Close'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='off', max_length=10),
        ),
    ]
